# compose for working with storm tape API
version: "3.9"

services:

  revproxy:
    build: 
      dockerfile: nginx_docker_revproxy/Dockerfile
    volumes:
      - ./nginx_docker_revproxy/nginx.conf:/usr/local/openresty-voms/nginx/conf/nginx.conf
      - ./nginx_docker_revproxy/scripts/:/usr/local/openresty-voms/nginx/njs/
      - ./nginx_docker_revproxy/certificates_for_https/:/usr/local/openresty-voms/nginx/conf/certs/
      # - /home/${USER}/.globus/:/usr/local/openresty-voms/nginx/conf/certs/
    ports:
      - "8081:443"

  opa:
    image: openpolicyagent/opa:0.39.0-istio
    volumes:
      - ./opa/policy.rego:/etc/opa/policy.rego
      - ./opa/data.json:/etc/opa/data.json
      - ./opa/config.yaml:/etc/opa/config.yaml
    command: [run, --server, /etc/opa/policy.rego, /etc/opa/data.json, -c, /etc/opa/config.yaml]

  service_server:
    image: baltig.infn.it:4567/giaco/storm-tape-poc:latest
    ports:
      - "80:8080"
    command: [/storm-tape-poc/build/storm-tape]